### ISSUE TITLE
WGAN error 

### ISSUE THREAD

**Issue by rlica** [yuanming-hu/exposure#24]
Any idea if this is related to the new version of tensorflow?

tensorflow                         1.0.1
tensorflow-gpu                 1.10.0

** WGAN
routine_loss (?, 1)
pg_loss (?, 1)
Traceback (most recent call last):
  File "evaluate.py", line 35, in <module>
    evaluate()
  File "evaluate.py", line 27, in evaluate
    net = GAN(cfg, restore=True)
  File "/home/licarazvan90/exposure/net.py", line 174, in __init__
    alpha_dist = tf.contrib.distributions.Uniform(low=0., high=1.)
TypeError: __init__() got an unexpected keyword argument 'low'

**Comment by yuanming-hu** [comment]
The code should work with tensorflow-gpu 1.10.0. Could you remove uninstall tensorflow 1.0.1 and try again? Just having the GPU version installed should be sufficient.

**Comment by rlica** [comment]
Thanks, indeed it works! Throught pip I removed tensorflow and still got some errors and then I changed to conda and everything worked fine. So it was some environment problem (note for others having similar errors).
Cheers!
